CREATE TABLE Estabelecimento (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    RazaoSocial NVARCHAR(200) NOT NULL,
    NomeFantasia NVARCHAR(200) NULL,
    Cnpj NVARCHAR(20) NULL,
    InscricaoEstadual NVARCHAR(30) NULL,
    Email NVARCHAR(150) NULL,
    Telefone NVARCHAR(30) NULL,
    WhatsApp NVARCHAR(30) NULL,
    Cep NVARCHAR(15) NULL,
    Logradouro NVARCHAR(200) NULL,
    Numero NVARCHAR(30) NULL,
    Complemento NVARCHAR(100) NULL,
    Bairro NVARCHAR(100) NULL,
    Cidade NVARCHAR(100) NULL,
    Uf CHAR(2) NULL,
    LogoUrl NVARCHAR(500) NULL,
    Ativo BIT NOT NULL DEFAULT 1,
    CriadoEm DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    AtualizadoEm DATETIME2 NULL
);

CREATE TABLE Cliente (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Nome NVARCHAR(200) NOT NULL,
    Documento NVARCHAR(20) NULL,
    Email NVARCHAR(150) NULL,
    Telefone NVARCHAR(30) NULL,
    WhatsApp NVARCHAR(30) NULL,
    Cep NVARCHAR(15) NULL,
    Logradouro NVARCHAR(200) NULL,
    Numero NVARCHAR(30) NULL,
    Complemento NVARCHAR(100) NULL,
    Bairro NVARCHAR(100) NULL,
    Cidade NVARCHAR(100) NULL,
    Uf CHAR(2) NULL,
    Observacao NVARCHAR(MAX) NULL,
    Ativo BIT NOT NULL DEFAULT 1,
    CriadoEm DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
);

CREATE TABLE Vendedor (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    EstabelecimentoId UNIQUEIDENTIFIER NOT NULL,
    UsuarioId UNIQUEIDENTIFIER NULL,
    Nome NVARCHAR(200) NOT NULL,
    Email NVARCHAR(150) NULL,
    Telefone NVARCHAR(30) NULL,
    PercentualComissaoPadrao DECIMAL(9,4) NOT NULL DEFAULT 0,
    Ativo BIT NOT NULL DEFAULT 1,
    CriadoEm DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),

);

CREATE TABLE Produto (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Codigo NVARCHAR(60) NULL,
    Nome NVARCHAR(200) NOT NULL,
    Descricao NVARCHAR(MAX) NULL,
    Unidade NVARCHAR(20) NOT NULL DEFAULT 'UN',
    ValorVenda DECIMAL(18,2) NOT NULL DEFAULT 0,
    Custo DECIMAL(18,2) NULL,
    Ativo BIT NOT NULL DEFAULT 1,
    CriadoEm DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Servico (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Codigo NVARCHAR(60) NULL,
    Nome NVARCHAR(200) NOT NULL,
    Descricao NVARCHAR(MAX) NULL,
    Valor DECIMAL(18,2) NOT NULL DEFAULT 0,
    Custo DECIMAL(18,2) NULL,
    Ativo BIT NOT NULL DEFAULT 1,
    CriadoEm DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE FormaPagamento (
    Id UNIQUEIDENTIFIER PRIMARY KEY,
    Nome NVARCHAR(100) NOT NULL,
    Tipo NVARCHAR(30) NOT NULL,
    Ativo BIT NOT NULL DEFAULT 1,
);